name: EssentialsXLight
version: '${project.version}'
main: me.alvsch.essentialsxlight.EssentialsXLight
api-version: 1.14
authors: [ Alvsch1 ]
commands:

  essentialsxlight:
    usage: "/<command>"
    description: "The main command for the plugin: EssentialsXLight"
    aliases: [exl, el, essentialslight]


  gamemode:
    usage: "/<command>"
    description: ""
    permission: ""
    aliases: [gm]
  gma:
    usage: "/<command>"
    description: ""
    permission: ""
  gmc:
    usage: "/<command>"
    description: ""
  gmsp:
    usage: "/<command>"
    description: ""
  gms:
    usage: "/<command>"
    description: ""

  tphere:
    usage: "/<command> <player>"
