name: EssentialsXLight
version: '${project.version}'
main: me.alvsch.essentialsxlight.EssentialsXLight
api-version: 1.14
authors: [ Alvsch1 ]
commands:

  essentialsxlight:
    usage: "/<command>"
    description: "The main command for the plugin: EssentialsXLight"
    aliases: []